### ISSUE TITLE
unit tests are failing

### ISSUE THREAD

**Issue by thescientist13** [kenzanlabs/react-seed#14]
Seeing this when running `yarn run test`
```bash
$ yarn run test
yarn run v0.21.3
$ jest --coverage --config ./jest.config.json
 PASS  src/index.spec.tsx
  ✓ use jsdom in this test file (4ms)

 FAIL  src/components/bootstrap/bootstrap.spec.tsx
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/jest-cli/build/TestRunner.js:110:20)

 FAIL  src/components/navigation/navigation.spec.tsx
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/jest-cli/build/TestRunner.js:110:20)

 FAIL  src/components/footer/footer.spec.tsx
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/jest-cli/build/TestRunner.js:110:20)

Test Suites: 3 failed, 1 passed, 4 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.54s, estimated 2s
Ran all test suites.
---------------------------|----------|----------|----------|----------|----------------|
File                       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------------|----------|----------|----------|----------|----------------|
All files                  |        0 |        0 |        0 |        0 |                |
 src                       |        0 |      100 |        0 |        0 |                |
  index.tsx                |        0 |      100 |        0 |        0 |... 10,13,14,16 |
  vendor.ts                |        0 |      100 |      100 |        0 |      1,2,3,4,5 |
 src/components/bootstrap  |        0 |        0 |        0 |        0 |                |
  bootstrap.tsx            |        0 |        0 |        0 |        0 |... 22,23,31,33 |
 src/components/footer     |        0 |        0 |        0 |        0 |                |
  footer.tsx               |        0 |        0 |        0 |        0 |... 26,27,35,37 |
 src/components/navigation |        0 |        0 |        0 |        0 |                |
  navigation.tsx           |        0 |        0 |        0 |        0 |... 21,22,34,36 |
---------------------------|----------|----------|----------|----------|----------------|
Jest: Coverage for statements (0%) does not meet global threshold (85%)
Jest: Coverage for branches (0%) does not meet global threshold (85%)
Jest: Coverage for lines (0%) does not meet global threshold (85%)
Jest: Coverage for functions (0%) does not meet global threshold (85%)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

A simple "it works" spec should be added to at least ensure the build will pass.  This will likely be an issue when #7 is worked on.

cc: @cxoltero

**Comment by thescientist13** [comment]
Any takers?  @mschmidt712 ?

**Comment by thescientist13** [comment]
@mschmidt712 
Let me know if you are interested, otherwise I will unassign and leave it up for grabs.  Although I think @cxoltero may resolving this as part of #24 ...

**Comment by thescientist13** [comment]
now that Jenkins is running CI, when this task gets enabled in the build, code coverage reporting should be added to the Jenkins build
<img width="1037" alt="screen shot 2017-07-19 at 7 56 03 am" src="https://user-images.githubusercontent.com/895923/28365781-e6c1780a-6c57-11e7-97eb-d3d9650a70c0.png">
